### ISSUE TITLE
Why does tagslam not work with official gtsam

### ISSUE THREAD

**Issue by nazneen-miko** [berndpfrommer/tagslam_root#16]
I was trying to run the tagslam algorithm with gtsam downloaded from the official website and the gtsam was not getting build successfully 
https://github.com/borglab/gtsam/archive/refs/tags/4.1.1.tar.gz

Is there a way to make tagslam work with official gtsam as I need gtsam for my other project in the same system

**Comment by berndpfrommer** [comment]
Can you provide error messages? Is tagslam not getting built or is gtsam not getting built?

**Comment by nazneen-miko** [comment]
I was getting this error when i use the official gtsam 
error: ‘struct gtsam::ISAM2Params’ has no member named ‘setEnableDetailedResults’

**Comment by berndpfrommer** [comment]
OK, so this is tagslam not compiling against the latest GTSAM. I have an upgrade to a later gtsam version on my todo list. Will try to work on it later this week.

**Comment by nazneen-miko** [comment]
So is there any earlier official gtsam version with which it compiles I will install that version in my system

**Comment by nazneen-miko** [comment]
Hey can you tell me the version of gtsam from official repo compatible with tagslam?

**Comment by berndpfrommer** [comment]
I believe it works with gtsam 4.0.3

**Comment by nazneen-miko** [comment]
ok let me try that

**Comment by nazneen-miko** [comment]
tagslam did work but my repo needs similarity3 which is not present in gtsam 4.0.3 version

**Comment by berndpfrommer** [comment]
I tried to move up to gtsam 4.1 but I get different results when I run tagslam. In some situation tagslam segfaults which is very concerning. I cannot provide a quick fix for it, the debugging is tedious.

**Comment by nazneen-miko** [comment]
yes i can understand the seg fault error is troublesome let me know if you come across any solution for this

**Comment by nazneen-miko** [comment]
Hey i tried with gtsam official 4.1.1 and i can build tagslam and also my project which needs similarity class successfully
