### ISSUE TITLE
Not able to run example quick test!

### ISSUE THREAD

**Issue by knazneen123** [berndpfrommer/tagslam_root#11]
Hey, 

I am trying to run the below command to test tagslam but its giving me this error, is it related to OpenCv version as I am using 4.5.4

roslaunch tagslam tagslam.launch bag:=`rospack find tagslam`/example/example.bag

... logging to /home/nazneen/.ros/log/d404ce2a-c6ce-11ec-ab04-453ce003fbd4/roslaunch-nazneen-miko-34089.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://192.168.29.51:40993/

SUMMARY
========

CLEAR PARAMETERS
 * /tagslam/

PARAMETERS
 * /rosdistro: noetic
 * /rosversion: 1.15.14
 * /tagslam/bag_file: /home/nazneen/ros...
 * /tagslam/bag_start_time: 0.0
 * /tagslam/camera_poses/cam0/pose/R: [1000000.0, 0.0, ...
 * /tagslam/camera_poses/cam0/pose/position/x: 0
 * /tagslam/camera_poses/cam0/pose/position/y: 0
 * /tagslam/camera_poses/cam0/pose/position/z: 0
 * /tagslam/camera_poses/cam0/pose/rotation/x: 0
 * /tagslam/camera_poses/cam0/pose/rotation/y: 0
 * /tagslam/camera_poses/cam0/pose/rotation/z: 0
 * /tagslam/cameras/cam0/camera_model: pinhole
 * /tagslam/cameras/cam0/distortion_coeffs: [-0.161604, 0.093...
 * /tagslam/cameras/cam0/distortion_model: radtan
 * /tagslam/cameras/cam0/intrinsics: [1404.917, 1403.5...
 * /tagslam/cameras/cam0/resolution: [1920, 1200]
 * /tagslam/cameras/cam0/rig_body: rig
 * /tagslam/cameras/cam0/rostopic: /pg_17274483/imag...
 * /tagslam/cameras/cam0/tagtopic: /detector/tags
 * /tagslam/has_compressed_images: False
 * /tagslam/max_number_of_frames: 1000000
 * /tagslam/playback_rate: 10.0
 * /tagslam/tagslam_config/bodies: [{'grasp_lab': {'...
 * /tagslam/tagslam_config/body_defaults/position_noise: 0.05
 * /tagslam/tagslam_config/body_defaults/rotation_noise: 0.01
 * /tagslam/tagslam_config/default_body: grasp_lab
 * /tagslam/tagslam_config/tagslam_parameters/max_num_incremental_opt: 50
 * /tagslam/tagslam_config/tagslam_parameters/max_subgraph_error: 50.0
 * /tagslam/tagslam_config/tagslam_parameters/minimum_viewing_angle: 12.0
 * /tagslam/tagslam_config/tagslam_parameters/optimizer_mode: fast
 * /tagslam/tagslam_config/tagslam_parameters/pixel_noise: 1.0
 * /tagslam/tagslam_config/tagslam_parameters/subgraph_abs_prior_position_noise: 0.1
 * /tagslam/tagslam_config/tagslam_parameters/subgraph_abs_prior_rotation_noise: 0.1
 * /tagslam/tagslam_config/tagslam_parameters/use_approximate_sync: False

NODES
  /
    tagslam (tagslam/tagslam_node)

ROS_MASTER_URI=http://192.168.29.51:11311

process[tagslam-1]: started with pid [34104]
[ INFO] [1651135910.779493611]: optimizer mode: fast
[ INFO] [1651135910.780733171]: added body grasp_lab with 1 tags
[ INFO] [1651135910.780763812]: added body rig with 0 tags
[ INFO] [1651135910.782309041]: found 1 cameras
[ INFO] [1651135910.782848906]: camera cam0 has known pose!
[ INFO] [1651135910.782911460]: no distance measurements found!
[ INFO] [1651135910.782944772]: no coordinate measurements found!
[ INFO] [1651135910.782971388]: no plane measurements found!
[ INFO] [1651135912.013876392]: reading from bag: /home/nazneen/rosProjects/tagslam_root/src/tagslam/example/example.bag
[ INFO] [1651135912.014693582]: number of tag   topics: 1
[ INFO] [1651135912.014774603]: number of image topics: 0
[ INFO] [1651135912.014827431]: number of odom  topics: 0
[ INFO] [1651135912.018673844]: frame 0 [1558997717.191335649] cam: cam0 sees tags: 
[ INFO] [1651135912.018875830]: frame 1 [1558997717.689639795] cam: cam0 sees tags: 
[ INFO] [1651135912.019256175]: frame 2 [1558997718.187753357] cam: cam0 sees tags: 
[ INFO] [1651135912.019372318]: frame 3 [1558997718.685203212] cam: cam0 sees tags: 
[ INFO] [1651135912.020334872]: new tag 3 attached to grasp_lab
[ INFO] [1651135912.020691273]: frame 4 [1558997719.179919103] cam: cam0 sees tags:  3
[ INFO] [1651135912.021231730]: [1558997719.179919103] subgraph err: 0, subgraph sum: 0
[ INFO] [1651135912.021342170]: graph after update: opt fac: 4 unopt fac: 1 opt vals: 4 unopt vals: 2
[ INFO] [1651135912.021724933]: frame 5 [1558997719.676376045] cam: cam0 sees tags:  3 0
[ERROR] [1651135912.026418853]: /tagslam: OpenCV(4.5.4) ../modules/calib3d/src/solvepnp.cpp:771: error: (-215:Assertion failed) (rsize == Size(1, 3) || rsize == Size(3, 1)) && (tsize == Size(1, 3) || tsize == Size(3, 1)) in function 'solvePnPGeneric'

[tagslam-1] process has died [pid 34104, exit code 255, cmd /home/nazneen/rosProjects/tagslam_root/devel/lib/tagslam/tagslam_node __name:=tagslam __log:=/home/nazneen/.ros/log/d404ce2a-c6ce-11ec-ab04-453ce003fbd4/tagslam-1.log].
log file: /home/nazneen/.ros/log/d404ce2a-c6ce-11ec-ab04-453ce003fbd4/tagslam-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete

**Comment by berndpfrommer** [comment]
what operating system are you running on?

**Comment by knazneen123** [comment]
I am using
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal

ROS : noetic

OpenCV : 4.5.4

**Comment by berndpfrommer** [comment]
Where does OpenCV 4.5.4 come from? Ubuntu 20.04 ships with OpenCV 4.2. Can you try compiling with OpenCV 4.2?

**Comment by knazneen123** [comment]
I built OpenCV 4.5.4 from source in my system as it was latest stable build and all other slam models were working in Ubuntu 20.04 with opencv 4.5.4 only tagslam gives error.
Sure as you suggested I will try adding opencv 4.2 and see if it runs or not, thanks for your support!

**Comment by berndpfrommer** [comment]
OK, that explains why I did not get these errors in testing. From the assertion it looks like something pretty fundamental is wrong, like the shape of the input arrays:
```
[ERROR] [1651135912.026418853]: /tagslam: OpenCV(4.5.4) ../modules/calib3d/src/solvepnp.cpp:771: error: (-215:Assertion 
failed) (rsize == Size(1, 3) || rsize == Size(3, 1)) && (tsize == Size(1, 3) || tsize == Size(3, 1)) in function 'solvePnPGeneric'
```
Can you go into init_pose.cpp and before line 397 (where solvePnP()) is called print out rvec.cols, rvec.rows, tvec.cols, tvec.rows. They should be 3 and 1. Thanks!

**Comment by knazneen123** [comment]
Hey, the size of vectors seems correct following is the output

rvec rows : 3; rvec cols : 1; tvec rows : 3; tvec cols : 1

**Comment by berndpfrommer** [comment]
Hmm, then why is it throwing that assertion error? Is it even bombing out in line 397? I don't know of another place that's calling solvePnP(). Is the size of one of the other inputs bad? Also, instead of D0 can you pass in an empty cv::Mat()?

**Comment by knazneen123** [comment]
Yes even i don't know exactly which line is causing the error, do you know any other debugging method or how we can use gdb to debug ros program and get the line causing error. Also, i will try the method you suggested and update you on monday, really appreciate your support

**Comment by berndpfrommer** [comment]
There are some ways to catch exceptions in gdb but I usually just put a print statement before and after the offending line.

**Comment by knazneen123** [comment]
yes even i do that writing print statements helps alot in debugging but in this case the line of error is unknown and even the file causing the error, do you think it's the init_pose.cc?

**Comment by berndpfrommer** [comment]
That's the only place I found in the whole source tree where an opencv routine related to pnp is called.

**Comment by knazneen123** [comment]
Hey, even tried passing D0 as empty and also tried initializing it in another way  cv::Mat1d D0(4, 4, 0.0); still same error 
I also verified the data stored in mat passed in solvePnp function, I am getting these values 
wp : -0.06 imu : -0.141978 eye : 1 D0 : 0 rvec : 2.19572 tvec : 0.00669117 even these values seems correct

**Comment by knazneen123** [comment]
After reinstalling opencv4.5.4 and removing opencv4.2 default which comes with ros-noetic package I am getting this error 

process[tagslam-2]: started with pid [170214]
[ INFO] [1651480666.460089428]: optimizer mode: fast
[ INFO] [1651480666.460931125]: added body grasp_lab with 1 tags
[ INFO] [1651480666.460954106]: added body rig with 0 tags
[ INFO] [1651480666.462012685]: found 1 cameras
[ INFO] [1651480666.462931622]: camera cam0 has known pose!
[ INFO] [1651480666.463002192]: no distance measurements found!
[ INFO] [1651480666.463062889]: no coordinate measurements found!
[ INFO] [1651480666.463116776]: no plane measurements found!
[ INFO] [1651480667.570702844]: reading from bag: /home/nazneen/rosProjects/tagslam_root/src/tagslam/example/example.bag
[ INFO] [1651480667.571492872]: number of tag   topics: 1
[ INFO] [1651480667.571561707]: number of image topics: 0
[ INFO] [1651480667.571600370]: number of odom  topics: 0
[ INFO] [1651480667.577174202]: frame 0 [1558997717.191335649] cam: cam0 sees tags: 
[ INFO] [1651480667.577361374]: frame 1 [1558997717.689639795] cam: cam0 sees tags: 
[ INFO] [1651480667.577837234]: frame 2 [1558997718.187753357] cam: cam0 sees tags: 
[ INFO] [1651480667.577939700]: frame 3 [1558997718.685203212] cam: cam0 sees tags: 
[ INFO] [1651480667.578863136]: new tag 3 attached to grasp_lab
[ INFO] [1651480667.579172997]: frame 4 [1558997719.179919103] cam: cam0 sees tags:  3
[ INFO] [1651480667.579708145]: [1558997719.179919103] subgraph err: 0, subgraph sum: 0
[ INFO] [1651480667.579804021]: graph after update: opt fac: 4 unopt fac: 1 opt vals: 4 unopt vals: 2
[ INFO] [1651480667.580162094]: frame 5 [1558997719.676376045] cam: cam0 sees tags:  3 0
[ERROR] [1651480667.592303274]: /tagslam: OpenCV(4.5.4) /home/nazneen/software_packages/opencv_module_4.5.4/opencv/modules/calib3d/src/undistort.dispatch.cpp:410: error: (-215:Assertion failed) CV_IS_MAT(_distCoeffs) && (_distCoeffs->rows == 1 || _distCoeffs->cols == 1) && (_distCoeffs->rows*_distCoeffs->cols == 4 || _distCoeffs->rows*_distCoeffs->cols == 5 || _distCoeffs->rows*_distCoeffs->cols == 8 || _distCoeffs->rows*_distCoeffs->cols == 12 || _distCoeffs->rows*_distCoeffs->cols == 14) in function 'cvUndistortPointsInternal'

**Comment by knazneen123** [comment]
Hey so after removing the default opencv 4.2 which gets installed with ros-noetic by referring this link https://zhuanlan-zhihu-com.translate.goog/p/400316912?_x_tr_sl=zh-CN&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=sc
and reinstalling opencv 4..5.4 and setting ldconfig path for this version it is now working
